### ISSUE TITLE
Harden GitHub settings

### ISSUE THREAD

**Issue by calebwherry** [robertdfrench/git-pr#16]
Some things I think we should do:

* Only allow trunk commits via PR
* Setup security policies
* Add aux files to repo like CONTRIB or other files that GH can use

Probably many more but definitely wanted to get the first 2 done.

**Comment by calebwherry** [comment]
FYI: I created this on the mobile GH app but I can't do anything other than put title and description. I can't label or attach to milestone or anything like that. @robertdfrench Just thought I would raise that to your attention.

**Comment by calebwherry** [comment]
Additionally:

* PRs must have a positive review and build before merge is allowed.
* Set merge settings on PR to trunk

**Comment by robertdfrench** [comment]
Done!
