### ISSUE TITLE
License in README points to wrong one

### ISSUE THREAD

**Issue by calebwherry** [robertdfrench/git-pr#21]

**Comment by robertdfrench** [comment]
hahaha woops! Copied and pasted

**Comment by calebwherry** [comment]
@robertdfrench were you able to fix this without a PR?

**Comment by robertdfrench** [comment]
I didn't try, but I don't think I should be able to because of the branch protection stuff we set up in #16 .

**Comment by robertdfrench** [comment]
@calebwherry doh! Forgot to submit this: https://github.com/robertdfrench/git-pr/pull/23

**Comment by calebwherry** [comment]
Oh, you created a branch and pushed but didn't create a PR, right?

**Comment by robertdfrench** [comment]
Correct, that's what I did initially, but then after you posted that
question I created this PR: https://github.com/robertdfrench/git-pr/pull/23
