### ISSUE TITLE
Integration tests clobber ~/.gitconfig

### ISSUE THREAD

**Issue by robertdfrench** [robertdfrench/git-pr#33]
At the moment, running `cargo test --release` on your local machine will overwrite these settings in your `~/.gitconfig`:

```console
$ git config user.name
Your Name
$ git config user.email
you@example.com
```

**Comment by calebwherry** [comment]
I believe this is because you added "--global" when you set the configs. I think it'll be fine if we just remove that.

When you typed that out earlier it crossed my mind to say something but for some reason I didn't. Bad pairing on my end, sorry!

**Comment by robertdfrench** [comment]
Aha! Yes, you are right! No worries, I'm glad you remembered. Will send a fix soon.
