### ISSUE TITLE
Update remote matching to be more general

### ISSUE THREAD

**Issue by calebwherry** [robertdfrench/git-pr#6]
Using origin can cause issues with others not using that wordage. Replace with "not slash" match as it can be anything.

_Originally posted by @calebwherry in https://github.com/robertdfrench/git-pr/pull/1#r725655510_

**Comment by calebwherry** [comment]
The current regex for this is:

Regex::new(r"^ *\** remotes/origin/")

But why can't it just be:

Regex::new(r"^ *\** remotes/")

@robertdfrench Does it even matter what comes after? Do we have to guarantee something is there? I can't think a case where the second one would fail.

**Comment by robertdfrench** [comment]
That would work for matching, but because the current design (which has problems like #7 anyway) uses the same regex for matching *and removal*, that change wouldn't work. It would lead to pr names looking like "origin/pr-name".
